/*

To setup a template we need to:

- Identify the number of rows we need for headers
- Identify the depth of header 

*/

// Use http://tools.medialab.sciences-po.fr/iwanthue/ to get a different color palette 
colors = ["#caecbc",
"#a6b79f",
"#bdd6bc",
"#a3c9a3",
"#d3f1d6",
"#88baa9",
"#97b1ab",
"#abc5bf",
"#b6eee2",
"#cde8e2",
"#79c6c1",
"#94d2cf",
"#a2e7ed",
"#83daf2",
"#bbe2ee",
"#6dc5dd",
"#99ceeb",
"#a4bccb",
"#b8cff2",
"#88aee1",
"#9db3d6",
"#cbd5e7",
"#cec9f3",
"#bcaad6",
"#e6d6ee",
"#e2c2f3",
"#c3b3cb",
"#f0c3dd",
"#e0b3c9",
"#e0c7ce",
"#88baa9",
"#97b1ab",
"#abc5bf",
"#b6eee2",
"#cde8e2",
"#79c6c1",
"#94d2cf",
"#a2e7ed",
"#83daf2",
"#bbe2ee",
"#6dc5dd",
"#99ceeb",
"#a4bccb",
"#b8cff2",
"#88aee1",
"#9db3d6",
"#cbd5e7",
"#cec9f3",
"#bcaad6",
"#e6d6ee",
"#e2c2f3",
"#c3b3cb",
"#f0c3dd",
"#e0b3c9",
"#e0c7ce"]

/*
* The schema map works with the output generated by ocdskit mapping-sheet (as of 2018-09-26)
* 
* It creates an array indexed by field paths that can be used to lookup mapping sheet information
*
* Instead of using column headings for this, it uses the column numbers, relying on the fact that 
* `ocdskit mapping-sheet` output follows a set column order. 
*
* It also identifies the maximum depth of the given schema (i.e. how many levels in the tree).
* This is used to work out how many rows to leave between field paths and the field titles when
* setting up a template. 
*/ 
function getSchemaMap(sheetName) {
  var schemaSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName)
  var schemaRange = schemaSheet.getRange(2,2,schemaSheet.getLastRow(),8).getValues()
  var schemaMap = {}
  var maxDepth = 0
  
  for(var i = 0; i < schemaRange.length; i++) {
    schemaMap[schemaRange[i][0]] = {
      "depth":schemaRange[i][0].split("/").length,
      "title": schemaRange[i][1],
      "description": schemaRange[i][2],
      "type": schemaRange[i][3],
      "range": schemaRange[i][4],
      "values": schemaRange[i][5],
      "links": schemaRange[i][6],
      "deprecated": schemaRange[i][7],
      "deprecationNotes": schemaRange[i][8],
    }
    if(schemaMap[schemaRange[i][0]]['depth'] > maxDepth) { maxDepth = schemaMap[schemaRange[i][0]]['depth']}
  }  
  
  return {'map':schemaMap,'maxDepth':maxDepth}
}


/*
* This function handles cases where a path does not exist in the map, returning just the last part of the path
*/

function getFieldAttribute(schemaMap,path,attribute) {
  if (schemaMap['map'][path] === undefined) {
    return path.split("/").pop()
  } else {
   return schemaMap['map'][path][attribute] || "" 
  }
}


/*
* This function establishes a spreadsheet template based on paths
*
* If singleColumn is set, then it only works on the column passed in the variable. 
*/ 

function layoutTemplate(singleColumn) {
  
  // We assume the presence of a mapping sheet with columns: section, path, title, description, type, range, values, links, deprecated, deprecationNotes
  // We build an object which maps from path to relevant information
  var schemaMap = getSchemaMap('mapping')
  var maxDepth = schemaMap['maxDepth']

  var sheet = SpreadsheetApp.getActiveSheet()
  var headers = sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0]

  //Get a copy of the header row without /0/ notation
  var mapHeaders = headers.map(function(item) { return item.replace(/\/[0-9]/g,"") })

  //Now we iterate through each column, setting up titles, color coding, and validation  
  var titles = []
  var descriptions = []
  var depth = 0
  var parent = ""
  var fontArray = []

  
  if(singleColumn) {
    startAt = singleColumn
    endAt = singleColumn + 1
  } else {
    startAt = 0
    endAt = mapHeaders.length
  }
  
  for(var m = startAt; m < endAt; m++) {

      
    if(singleColumn) {
      if(singleColumn === m) {
        titles.push(schemaMap['map'][mapHeaders[m]]['title'])
        descriptions.push(schemaMap['map'][mapHeaders[m]]['description'])
        fontArray.push("bold")      
      }
    } else {
      titles.push(getFieldAttribute(schemaMap,mapHeaders[m],'title')) //If we are missing the path from our map, use the last part of the path
      descriptions.push(getFieldAttribute(schemaMap,mapHeaders[m],'description'))
      fontArray.push("bold")
      
        //When the parent changes we want to write out the object details, and color in the range.
        var currentParent = mapHeaders[m].split("/")[mapHeaders[m].split("/").length - 2]
  
        if(currentParent != parent) {
          depth = mapHeaders[m].split("/").length
          parent = mapHeaders[m].split("/")[mapHeaders[m].split("/").length - 2]
          var object = mapHeaders[m].substring(0, mapHeaders[m].lastIndexOf('/'))
          sheet.getRange(depth +1,m + 1 ,1,1).setValue(getFieldAttribute(schemaMap,object,'title')).setFontWeight("bold")
          sheet.getRange(depth +1,m + 1 ,1,1).setNote(getFieldAttribute(schemaMap,object,'description'))
         
          //We select the next entry from our array of colors
          color = colors.pop()
          sheet.getRange(depth+1,m+1,(maxDepth-depth) +1,(sheet.getLastColumn() - m)).setBackground(color)
          sheet.getRange(depth+1,m+1,(maxDepth-depth) +1,(sheet.getLastColumn() - m)).setBorder(true,true,true,true,true,true,color,SpreadsheetApp.BorderStyle.SOLID)
        }
      }
      //Now we set up our validations    
      validationRange = sheet.getRange(maxDepth +2, m+1, sheet.getLastRow(),1)
      
      if(getFieldAttribute(schemaMap,mapHeaders[m],'type')== 'number') {
       validationRange.setDataValidation(SpreadsheetApp.newDataValidation()
          .setAllowInvalid(true)
          .requireNumberBetween(-99999999, 999999999)
          .build());
      } 
    
      if(getFieldAttribute(schemaMap,mapHeaders[m],'values')== 'date-time') {
       validationRange.setDataValidation(SpreadsheetApp.newDataValidation()
          .setAllowInvalid(true)
          .requireDate()
          .build());
      }
    
      if(getFieldAttribute(schemaMap,mapHeaders[m],'values') == 'uri') {
       validationRange.setDataValidation(SpreadsheetApp.newDataValidation()
          .setAllowInvalid(true)
          .requireTextIsUrl()
          .build());
      } 
    
      if(getFieldAttribute(schemaMap,mapHeaders[m],'type') == 'boolean') {
       validationRange.setDataValidation(SpreadsheetApp.newDataValidation()
          .setAllowInvalid(true)
          .requireValueInList(['','True', 'False'])
          .build());
        validationRange.setNumberFormat('@');
        
        conditionalFormatRules = sheet.getConditionalFormatRules();
        conditionalFormatRules.splice(conditionalFormatRules.length - 1, 0, SpreadsheetApp.newConditionalFormatRule()
        .setRanges([validationRange])
        .whenTextContains('True')
        .setBold(true)
        .build());
        conditionalFormatRules.splice(conditionalFormatRules.length - 1, 0, SpreadsheetApp.newConditionalFormatRule()
        .setRanges([validationRange])
        .whenTextContains('False')
        .setItalic(true)
        .setFontColor('#666666')
        .build());
        sheet.setConditionalFormatRules(conditionalFormatRules);
        
      } 
    
    
    
      if(getFieldAttribute(schemaMap,mapHeaders[m],'values').indexOf('Codelist:') != -1) {
        var codelist = getFieldAttribute(schemaMap,mapHeaders[m],'values').replace("Codelist: ","").split(", ")
        validationRange.setDataValidation(SpreadsheetApp.newDataValidation()
          .setAllowInvalid(true)
          .requireValueInList(codelist, true)
          .build());
      }

  }

  //Now we add our row of column headers.
  var titleRow = sheet.getRange(maxDepth+1,startAt+1,1,(endAt-startAt)).setValues([titles]).setFontWeights([fontArray])
  sheet.getRange(maxDepth+1,startAt+1,1,(endAt-startAt)).setNotes([descriptions])
}


/*
* When we want to update the validation for a single column, this function can be used
* to set titles and validation for the currently selected column.
*/ 
function setCurrentColValidation() {
    var col = SpreadsheetApp.getActiveSheet().getActiveCell().getColumn()
    layoutTemplate(col-1)
  
}

/*
* This function sets up column grouping
*/

function setupGroups(){
  var schemaMap = getSchemaMap('mapping')
  
  var sheet = SpreadsheetApp.getActiveSheet()
  var headers = sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0]

  //Get a copy of the header row without /0/ notation
  var mapHeaders = headers.map(function(item) { return item.replace(/\/[0-9]/g,"") })
  //Reset all groupings
  sheet.getRange(1,1,1,sheet.getLastColumn()).shiftColumnGroupDepth(-10)
  
  var parent = ""

  //Iterate through at depth N
  
  
  //We iterate through to each new parent  
  //TODO - USE MAP HEADERS DEPTH OF THE PARENT TO WORK OUT WHAT WE SHOULD BE COMPARING - 
  // INSTEAD OF COMPARING TO THE END OF THE PATH STRING AS WE ARE AT PRESENT
  // Start at maxDepth. Go through until value at MaxDepth changes
  
  for(depth = 0; depth < schemaMap['maxDepth']; depth++) {
     for(p = 0; p < mapHeaders.length - 1; p++) {
        Logger.log(mapHeaders[p].split("/")[depth])
        // Check if we have two columns with the same value at this depth. If so, we want to group them, so we'll want to keep going until we find a different value
        if(mapHeaders[p].split("/")[depth] && !startCol && mapHeaders[p].split("/")[depth] == mapHeaders[p+1].split("/")[depth]) {
           var startCol = p
           var currentGroup = mapHeaders[p].split("/")[depth]
        }
        if(currentGroup && (currentGroup != mapHeaders[p+1].split("/")[depth])) {
           Logger.log(currentGroup + " runs from " + startCol + " to " + p) 
           sheet.getRange(1,startCol+2,1,p-startCol).shiftColumnGroupDepth(1)
           startCol = null
           currentGroup = null
        }
     }
  }  
}

/**
 * Takes a positive integer and returns the corresponding column name.
 * @param {number} num  The positive integer to convert to a column name.
 * @return {string}  The column name.
 *
 * Taken from http://cwestblog.com/2013/09/05/javascript-snippet-convert-number-to-column-name/ 
 */
function toColumnName(num) {
  for (var ret = '', a = 1, b = 26; (num -= a) >= 0; a = b, b *= 26) {
    ret = String.fromCharCode(parseInt((num % b) / a) + 65) + ret;
  }
  return ret;
}

/*
* This function creates a lookup for any Organization fields to the Organization table
*/
function addOrganizationLookup() {
   var schemaMap = getSchemaMap('mapping')
   var dataRowStartsAt = schemaMap['maxDepth'] + 2 
   var sheet = SpreadsheetApp.getActiveSheet()
   var headers = sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0]

   //Get a copy of the header row without /0/ notation
   var mapHeaders = headers.map(function(item) { return item.replace(/\/[0-9]/g,"") })
  
   var selectCols = []
   var lastValidationSet = ""
   var setValidationFor = ""
   
   for(i = 0; i < mapHeaders.length -1; i++) {
    path = mapHeaders[i]
    validationRange = sheet.getRange(dataRowStartsAt, i+1, sheet.getLastRow()-(dataRowStartsAt+1),1)

    
    if(path.indexOf('Organization/') !== -1) {
      field = path.split("Organization/").pop()
      if(field == 'name') {
         var orgNameField = i;  
         validationRange.setDataValidation(SpreadsheetApp.newDataValidation()
            .setAllowInvalid(true)
            .requireValueInRange(sheet.getRange('Organizations!$A:$A'), true)
            .build());
      } else {
        if(getOrgLookupCol(field) > 1) {
          selectCols.push(toColumnName(getOrgLookupCol(field)))
        } else {          
          setValidationFor = path.split("/").shift()
        }
      }
      
      
    } else {
      if(orgNameField) {
       setValidationFor = path.split("/").shift()
      }
    }
    
     if(setValidationFor && setValidationFor != lastValidationSet) {
        // We have hit a point where the top-level has changed, so time to output our query.
        //Time to write our query out and reset the array 
        sheet.getRange(dataRowStartsAt,orgNameField+2).setFormula("=Query(Organizations!A:AH,\"SELECT " + selectCols.join(", ") + " WHERE A = '\" & "+ toColumnName(orgNameField + 1) + String(dataRowStartsAt) + "& \"' LIMIT 1\",false)");
        sourceRange = sheet.getRange(dataRowStartsAt,orgNameField+2)
        validationRange = sheet.getRange(dataRowStartsAt + 1,orgNameField+2,sheet.getLastRow()-(dataRowStartsAt + 1))
        sourceRange.copyTo(validationRange)
        selectCols = []
        delete orgNameField
        lastValidationSet = setValidationFor
       
      }
    
  }   
}
    
function getOrgLookupCol(field) {
 orgsheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Organizations");
 orgHeadings = orgsheet.getRange(1,1,1,orgsheet.getLastColumn()).getValues();
 col = orgHeadings[0].indexOf(field)
 return col + 1
}